### ISSUE TITLE
Tom/Maciej -remove ' More about' link to top bar. Change name 'Hello' to ' About'

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#395] opened 2019-08-19 06:31 UTC
Hi Tom, Maciej, I've merged 'more about' wix page  so no page link here- see also issue 394.   could you possibly remove this from the top bar as soon as you can? and also rename ' hello' as 'About' thanks

**Comment by mz8i** [comment] 2019-09-04 14:32
@polly64 can we get in touch about me potentially getting access to the WIX site? Would help ahead of launch if I can also make some small modifications

**Comment by polly64** [comment] 2019-09-04 14:46
hi Maciej sure - Dom has the password can it wait til he's back or do u need it now?


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ



________________________________

**Comment by mz8i** [comment] 2019-09-04 14:50
it's ok I will get in touch with him, thank you

**Comment by polly64** [comment] 2019-09-04 14:59
if u get stuck just let me know


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ



________________________________

**Comment by dominijk** [comment] 2019-09-06 13:20
Duplicate of #394 ?

**Comment by mz8i** [comment] 2019-09-06 13:21
Closely related so let's move discussion to #394, closing here.

**Closed by mz8i** 2019-09-06 13:21 UTC
