### ISSUE TITLE
post october - data showcase 2016 reference image

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#374] opened 2019-08-11 07:16 UTC
![alanbaxter](https://user-images.githubusercontent.com/42236514/62830997-3b2fd580-bc10-11e9-8b74-3d6780ed2d3d.JPG)

**Comment by tomalrussell** [comment] 2019-10-04 16:08
Duplicate of #340

**Closed by tomalrussell** 2019-10-04 16:08 UTC
Labels: needs-design
