### ISSUE TITLE
Post oct - advanced viewing page layout draft from 2017

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#373] opened 2019-08-11 07:07 UTC
![ViewMapsChapter](https://user-images.githubusercontent.com/42236514/62830927-ea6bad00-bc0e-11e9-9aa1-b21342238899.JPG)

**Comment by dominijk** [comment] 2019-08-12 13:40
@polly64 To confirm that advanced viewing is applying things like multiple filters to the data.

**Comment by polly64** [comment] 2019-08-12 13:46
yes exactly  - I'm imagining for advanced viewing this is after october and somewhere we are saying ' advanced viewing is coming soon

**Comment by dominijk** [comment] 2019-08-12 13:51
@tomalrussell I think we've discuss this briefly before. Adding the API label but there's also a question on what load this adds to the server to generate bespoke style sets, alongside the front end work. Another argument for getting OS to allow us to use vectortiles.

**Comment by tomalrussell** [comment] 2019-08-12 13:52
Yes - needs motivation with clear use cases, and time spent evaluating possible design solutions.

**Comment by tomalrussell** [comment] 2019-10-04 17:12
Duplicate of #18

**Closed by tomalrussell** 2019-10-04 17:12 UTC
Labels: needs-design, top-level, ui:community, ui:mobile
