### ISSUE TITLE
New sub category: Form type 

### ISSUE THREAD

**Issue by polly64** [tomalrussell/colouring-london#353] opened 2019-08-07 13:10 UTC
Hi Dom on my desk is Phil steadman's built forms book.  On page 3 i think he talks about ' active' types (related to use) e.g is it a house, warehouse etc  and ' form' types' e.g. is it  detached or semi detached building - would be great if we could collect both in the dropdowns- this would also solve the problem of where we put that the detached etc data as didn't fit well in Size and Shape

**Comment by dominijk** [comment] 2019-08-07 17:09
@polly64 What's the relationship between active type and land use category? Is active type effectively landuse class?

**Comment by dominijk** [comment] 2019-08-07 17:10
Note to self: Form type will be prepopulated from UCL Energy data

**Comment by polly64** [comment] 2019-08-07 19:21
active type is 'original land use' not current land use

**Comment by dominijk** [comment] 2019-08-07 19:52
@polly64 Might that not be confusing? I'd associate active with current not past use

**Comment by polly64** [comment] 2019-08-07 20:00
I think Phil might have used ' activity type' Basically we just need to get across that we are collecting info a) on the generic form  which could including many buildings each with  differernt uses  e.g a semi detached building or a end of terrace structure , but also on the  very specific form related to use e.g a warehouse typology, hospital typology.  this typology won't necessarily be connected to the current use though e.g warehouse transitioning to flat or office. does that sound ok?


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ




________________________________

**Comment by dominijk** [comment] 2019-08-30 15:31
Duplicate of #358 and #363

**Closed by dominijk** 2019-08-30 15:31 UTC
Labels: cat:land use, cat:size and shape, data
